// <auto-generated />
namespace Seeker.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class intial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intial));
        
        string IMigrationMetadata.Id
        {
            get { return "201411242156253_intial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
